### ISSUE TITLE
Error CS0234, CS0246

### ISSUE THREAD

**Issue by MaxFps** [pollfish/unity-plugin-pollfish#1]
I use Unity2018.4.12f1, I just import the API into UNity which has shown these 4 errors. I use the Android platform, I deleted using IOS, but the remaining error I do not understand, Please help me

1. Assets\Editor\PollfishBuildPostprocessor.cs(8,19): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)
2. Assets\Editor\PollfishBuildPostprocessor.cs(10,19): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)
3. Assets\Editor\PollfishBuildPostprocessor.cs(61,46): error CS0246: The type or namespace name 'PBXProject' could not be found (are you missing a using directive or an assembly reference?)
4. Assets\Editor\PollfishBuildPostprocessor.cs(71,40): error CS0246: The type or namespace name 'PBXProject' could not be found (are you missing a using directive or an assembly reference?)

**Comment by kaspanvo** [comment]
Hello, our plugin is for both Android and iOS.

If you do not want to use the iOS plugin when you import Pollfish plugin, you can choose which files to import. In your case you can uncheck and avoid importing PollfishBuildPostprocessor.cs in the Editor folder.

Kind reminder also that Pollfish does not work on Editor.

Hope that helps.
