### ISSUE TITLE
The sdk doesn't work anymore with the latest android sdk

### ISSUE THREAD

**Issue by 00christian00** [pollfish/unity-plugin-pollfish#3]
I upgraded to target sdk 30 and I noticed I am not able to run the example anymore, the ads gets never loaded.
I spent the whole day trying to figure out the issue but I give up, it must be on your end.
I think it's not able to connect anymore to your server. I tried to enable usescleartexttraffic but still doesn't work.
All it says is that there are no survey, no error, nothing.
The only clue is some message that pop up at start "I/System.out: (HTTPLog)-Static: isSBSettingEnabled false"

**Comment by fotism23** [comment]
Hello @00christian00 

We tried to replicate the issue you are facing but the Unity plugin is working as expected.

Have you tried to export an Android project (by checking the "Export project" setting in Unity's Build Settings), open it with Android Studio and run the app?

If the error persists please contact our support so we can review your integration and troubleshoot your issue.
