### ISSUE TITLE
Multiple commands produce Pollfish.framework in Unity Cloud

### ISSUE THREAD

**Issue by DmitrySharov** [pollfish/unity-plugin-pollfish#5]
Hello.
After a clean install of Pollfish in a project, an error occurs when building in Unity Cloud.
The error indicates that some file in the framework is iterating and creating a multiple call.
I'm actively trying to find at least some information, but so far without success.

Initialize engine version: 2021.2.11f1
Building with Xcode 13.2.1

`Multiple commands produce '/BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-foomoxpllhripmfogtckblyhpaut/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/APPLICATION_PATH/NSS-Game.app/Frameworks/Pollfish.framework':`
```
20789: ▸ 1) Target 'Unity-iPhone' has copy command from '/BUILD_PATH/red-rift-games.nss-game.dev-ios/temp20220408-5111-lgusjp/Pods/Pollfish/Pollfish.xcframework/ios-arm64_armv7/Pollfish.framework' to '/BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-foomoxpllhripmfogtckblyhpaut/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/APPLICATION_PATH/NSS-Game.app/Frameworks/Pollfish.framework'
20790: ▸ 2) That command depends on command in Target 'Unity-iPhone': script phase “[CP] Embed Pods Frameworks”
20791: ▸ warning: duplicate output file '/BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-foomoxpllhripmfogtckblyhpaut/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/APPLICATION_PATH/NSS-Game.app/Frameworks/Pollfish.framework' on task: PhaseScriptExecution [CP] Embed Pods Frameworks /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-foomoxpllhripmfogtckblyhpaut/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Script-9180C25F3FA5E0B8F1B2AB0A.sh (in target 'Unity-iPhone' from project 'Unity-iPhone')
```

**Comment by fotism23** [comment]
Hello @DmitrySharov 
Which version of Pollfish Unity Plugin are you using?

**Comment by DmitrySharov** [comment]
> Hello @DmitrySharov Which version of Pollfish Unity Plugin are you using?

v6.1.7
I see that 4 days ago they made an update.
Now I'll try to install it. Can it help?

**Comment by DmitrySharov** [comment]
```
20908: ▸ ❌;  error: Multiple commands produce '/BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-dxmnzheqybvyjhcooljfecstfgor/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/APPLICATION_PATH/NSS-Game.app/Frameworks/Pollfish.framework':
20909: ▸     duplicate output file '/BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-dxmnzheqybvyjhcooljfecstfgor/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/APPLICATION_PATH/NSS-Game.app/Frameworks/Pollfish.framework' on task: PhaseScriptExecution [CP] Embed Pods Frameworks /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-dxmnzheqybvyjhcooljfecstfgor/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Script-5F7176CBA6DF531D82B72F78.sh (in target 'Unity-iPhone' from project 'Unity-iPhone')
```
Unfortunately the update didn't fix the problem.

**Comment by fotism23** [comment]
1. Do you have any other plugins imported into your project? If possible please provide a list in order to try and replicate the issue. Sometimes with the External Dependency Manager one dependency might affect the other. 
2. Does this also happen when you build on your local machine or is it a cloud build only issue?
3. Can you provide a screenshot of your iOS Resolver Settings. From the top menu bar navigate to Assets -> External Dependency Manager -> iOS Resolver  -> Settings

**Comment by DmitrySharov** [comment]
1. Yes, Facebook SDK is also used. 
Specifically: facebook is used for authorization, but facebook does not give errors during assembly
2. Unfortunately, there is no macbook in order to assemble the build fully.
When locally assembling the x-code of the project, no errors occur.
With a cloud build, an error occurs after the cloud build starts building using the x-code builder
3. 
<img width="299" alt="image" src="https://user-images.githubusercontent.com/79997060/163788541-3e207f4c-dc29-4339-98d0-3a0ab282ce53.png">

**Comment by fotism23** [comment]
Please try disabling the "Link frameworks statically" option in the iOS Resolver settings and give it another try.
If Facebook SDK integration prevents you from disabling this option please let us know in order to provide a workaround

**Comment by fotism23** [comment]
Hello @DmitrySharov 
Did this resolve your issue or will you need further support?
Thanks!

**Comment by DmitrySharov** [comment]
@fotism23 Thanks for the support. 
Changing this setting helped.

**Comment by Inspyro** [comment]
Can you fix this in the next version? Google recommends this setting, so it is expected that pollfish works regardless

**Comment by fotism23** [comment]
Hello @Inspyro 
Thanks for the report, we will provide a fix regarding this issue on our next release

**Comment by fotism23** [comment]
Hello @Inspyro
Sorry for the late response

Could you please try the attached PollfishUnityPlugin and check if the issue has been resolved since we were unable to replicate the issue in our tests.

[Pollfish Unity Plugin v6.1.9.zip](https://github.com/pollfish/unity-plugin-pollfish/files/9233924/Pollfish.Unity.Plugin.v6.1.9.zip)

Thanks
